# Generated by go2rpm 1
%bcond_without check

# https://github.com/schollz/closestmatch
%global goipath         github.com/schollz/closestmatch
Version:                2.1.0

%gometa

%global common_description %{expand:
Golang library for fuzzy matching within a set of strings :page_with_curl:.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Golang library for fuzzy matching within a set of strings :page_with_curl:

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Thu Apr 09 18:17:41 +03 2020 ElXreno <elxreno@gmail.com> - 2.1.0-1
- Initial package

