# Generated by go2rpm 1
%bcond_without check

# https://github.com/arduino/arduino-cli
%global goipath         github.com/arduino/arduino-cli
Version:                0.9.0
%global tag             0.9.0

%gometa

%global common_description %{expand:
Arduino command line interface.}

%global golicenses      LICENSE.txt
%global godocs          README.rst CONTRIBUTING.md legacy/builder/ctags/test_\\\
                        data/TestCTagsRunnerSketchWithMultifile.txt legacy/bu\\\
                        ilder/ctags/test_data/TestCTagsParserNamespace.txt le\\\
                        gacy/builder/ctags/test_data/TestCTagsParserShouldLis\\\
                        tTemplates2.txt legacy/builder/ctags/test_data/TestCT\\\
                        agsRunnerSketchWithClassFunction.txt legacy/builder/c\\\
                        tags/test_data/TestCTagsParserShouldDealWithMacros.tx\\\
                        t legacy/builder/ctags/test_data/TestCTagsParserShoul\\\
                        dListTemplates.txt legacy/builder/ctags/test_data/Tes\\\
                        tCTagsParserShouldDealFunctionWithDifferentSignatures\\\
                        .txt legacy/builder/ctags/test_data/TestCTagsParserDe\\\
                        faultArguments.txt legacy/builder/ctags/test_data/Tes\\\
                        tCTagsParserShouldDealWithClasses.txt legacy/builder/\\\
                        ctags/test_data/TestCTagsParserClassMembersAreFiltere\\\
                        dOut.txt legacy/builder/ctags/test_data/TestCTagsPars\\\
                        erFunctionPointersNoIndirect.txt legacy/builder/ctags\\\
                        /test_data/TestCTagsParserShouldListPrototypes.txt le\\\
                        gacy/builder/ctags/test_data/TestCTagsParserFunctionP\\\
                        ointer.txt legacy/builder/ctags/test_data/TestCTagsPa\\\
                        rserFunctionPointers.txt legacy/builder/ctags/test_da\\\
                        ta/TestCTagsParserStructWithFunctions.txt legacy/buil\\\
                        der/ctags/test_data/TestCTagsParserStatic.txt legacy/\\\
                        builder/ctags/test_data/TestCTagsParserShouldDealWith\\\
                        Structs.txt\\\
                        legacy/builder/hardware/platform.keys.rewrite.txt

Name:           %{goname}
Release:        1%{?dist}
Summary:        Arduino command line interface

License:        GPL-3.0-only
# FIXME: Upstream uses unknown SPDX tag GPL-3.0-only!
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/arduino/board-discovery)
BuildRequires:  golang(github.com/arduino/go-paths-helper)
BuildRequires:  golang(github.com/arduino/go-properties-orderedmap)
BuildRequires:  golang(github.com/arduino/go-timeutils)
BuildRequires:  golang(github.com/arduino/go-win32-utils)
BuildRequires:  golang(github.com/cmaglie/pb)
BuildRequires:  golang(github.com/codeclysm/extract)
BuildRequires:  golang(github.com/fatih/color)
BuildRequires:  golang(github.com/fsnotify/fsnotify)
BuildRequires:  golang(github.com/go-errors/errors)
BuildRequires:  golang(github.com/golang/protobuf/proto)
BuildRequires:  golang(github.com/golang/protobuf/ptypes/struct)
BuildRequires:  golang(github.com/mattn/go-colorable)
BuildRequires:  golang(github.com/pkg/errors)
BuildRequires:  golang(github.com/pmylund/sortutil)
BuildRequires:  golang(github.com/rifflock/lfshook)
BuildRequires:  golang(github.com/schollz/closestmatch)
BuildRequires:  golang(github.com/sirupsen/logrus)
BuildRequires:  golang(github.com/spf13/cobra)
BuildRequires:  golang(github.com/spf13/cobra/doc)
BuildRequires:  golang(github.com/spf13/jwalterweatherman)
BuildRequires:  golang(github.com/spf13/viper)
BuildRequires:  golang(github.com/stretchr/testify/assert)
BuildRequires:  golang(go.bug.st/cleanup)
BuildRequires:  golang(go.bug.st/downloader)
BuildRequires:  golang(go.bug.st/relaxed-semver)
BuildRequires:  golang(go.bug.st/serial)
BuildRequires:  golang(golang.org/x/net/context)
BuildRequires:  golang(golang.org/x/text/transform)
BuildRequires:  golang(golang.org/x/text/unicode/norm)
BuildRequires:  golang(google.golang.org/grpc)
BuildRequires:  golang(google.golang.org/grpc/codes)
BuildRequires:  golang(google.golang.org/grpc/status)
BuildRequires:  golang(gopkg.in/yaml.v2)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/require)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%build
%gobuild -o %{gobuilddir}/bin/arduino-cli %{goipath}
for cmd in legacy/builder/client client_example; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE.txt
%doc README.rst CONTRIBUTING.md
%doc legacy/builder/ctags/test_data/TestCTagsRunnerSketchWithMultifile.txt
%doc legacy/builder/ctags/test_data/TestCTagsParserNamespace.txt
%doc legacy/builder/ctags/test_data/TestCTagsParserShouldListTemplates2.txt
%doc legacy/builder/ctags/test_data/TestCTagsRunnerSketchWithClassFunction.txt
%doc legacy/builder/ctags/test_data/TestCTagsParserShouldDealWithMacros.txt
%doc legacy/builder/ctags/test_data/TestCTagsParserShouldListTemplates.txt
%doc legacy/builder/ctags/test_data/TestCTagsParserShouldDealFunctionWithDifferentSignatures.txt
%doc legacy/builder/ctags/test_data/TestCTagsParserDefaultArguments.txt
%doc legacy/builder/ctags/test_data/TestCTagsParserShouldDealWithClasses.txt
%doc legacy/builder/ctags/test_data/TestCTagsParserClassMembersAreFilteredOut.txt
%doc legacy/builder/ctags/test_data/TestCTagsParserFunctionPointersNoIndirect.txt
%doc legacy/builder/ctags/test_data/TestCTagsParserShouldListPrototypes.txt
%doc legacy/builder/ctags/test_data/TestCTagsParserFunctionPointer.txt
%doc legacy/builder/ctags/test_data/TestCTagsParserFunctionPointers.txt
%doc legacy/builder/ctags/test_data/TestCTagsParserStructWithFunctions.txt
%doc legacy/builder/ctags/test_data/TestCTagsParserStatic.txt
%doc legacy/builder/ctags/test_data/TestCTagsParserShouldDealWithStructs.txt
%doc legacy/builder/hardware/platform.keys.rewrite.txt
%{_bindir}/*

%gopkgfiles

%changelog
* Thu Apr 09 15:50:09 +03 2020 ElXreno <elxreno@gmail.com> - 0.9.0-1
- Initial package

