# Generated by go2rpm 1
%bcond_without check

# https://github.com/pmylund/sortutil
%global goipath         github.com/pmylund/sortutil
%global commit          abeda66eb583fac2d8d98d3d2e6fbd5c67af7947

%gometa

%global common_description %{expand:
Nested, case-insensitive, and reverse sorting for Go.}

%global golicenses      LICENSE
%global godocs          README

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Nested, case-insensitive, and reverse sorting for Go

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Thu Apr 09 18:13:56 +03 2020 ElXreno <elxreno@gmail.com> - 0-0.1.20200409gitabeda66
- Initial package

