# Generated by go2rpm 1
%bcond_without check

# https://github.com/rifflock/lfshook
%global goipath         github.com/rifflock/lfshook
Version:                2.4

%gometa

%global common_description %{expand:
A local file system hook for golang logrus logger.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        A local file system hook for golang logrus logger

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/sirupsen/logrus)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Thu Apr 09 18:16:14 +03 2020 ElXreno <elxreno@gmail.com> - 2.4-1
- Initial package

