# Generated by go2rpm 1
%bcond_without check

# https://github.com/fluxio/iohelpers
%global goipath         github.com/fluxio/iohelpers
%global commit          3a4dd67a94d215a3fe44f84c98b34472627fd3a3

%gometa

%global common_description %{expand:
Flux iohelper utilities.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Flux iohelper utilities

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

%if %{with check}
# Tests
BuildRequires:  golang(github.com/smartystreets/goconvey/convey)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Thu Apr 09 20:02:03 +03 2020 ElXreno <elxreno@gmail.com> - 0-0.1.20200409git3a4dd67
- Initial package

