# Generated by go2rpm 1
# Disable check by default
%bcond_with check

# https://github.com/fluxio/multierror
%global goipath         github.com/fluxio/multierror
%global commit          9c68d39025e5c354adb4da3d75f3c8ee6f8c6a02

%gometa

%global common_description %{expand:
Flux error helper utilities.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Flux error helper utilities

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/fluxio/iohelpers/line)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Thu Apr 09 16:03:08 +03 2020 ElXreno <elxreno@gmail.com> - 0-0.1.20200409git9c68d39
- Initial package

