# Generated by go2rpm 1
%bcond_without check

# https://go.bug.st/serial.v1/enumerator
%global goipath         go.bug.st/serial.v1/enumerator
%global forgeurl        https://github.com/bugst/go-serial
Version:                1.0.0

%gometa

%global common_description %{expand:
A cross-platform serial library for go-lang.}

Name:           %{goname}
Release:        1%{?dist}
Summary:        A cross-platform serial library for go-lang

License:        BSD

URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/creack/goselect)
BuildRequires:  golang(go.bug.st/serial)
BuildRequires:  golang(go.bug.st/serial/enumerator)
BuildRequires:  golang(go.bug.st/serial/unixutils)
BuildRequires:  golang(golang.org/x/sys/unix)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Thu Apr 09 17:21:26 +03 2020 ElXreno <elxreno@gmail.com> - 1.0.0-1
- Initial package

