# Generated by go2rpm 1
%bcond_without check

# https://github.com/iancoleman/strcase
%global goipath         github.com/iancoleman/strcase
%global commit          16388991a33441046539eb716cff4d294d556c70

%gometa

%global common_description %{expand:
A golang package for converting to snake_case or CamelCase.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        A golang package for converting to snake_case or CamelCase

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Thu Apr 09 19:30:17 +03 2020 ElXreno <elxreno@gmail.com> - 0-0.1.20200409git1638899
- Initial package

