# Generated by go2rpm 1
%bcond_without check

# https://github.com/envoyproxy/protoc-gen-validate
%global goipath         github.com/envoyproxy/protoc-gen-validate
Version:                0.1.0

%gometa

%global common_description %{expand:
Protoc plugin to generate polyglot message validators.}

%global golicenses      LICENSE NOTICE
%global godocs          CODE_OF_CONDUCT.md rule_comparison.md README.md\\\
                        gogoproto/README.md java/RELEASING.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Protoc plugin to generate polyglot message validators

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/gogo/protobuf/proto)
BuildRequires:  golang(github.com/gogo/protobuf/types)
BuildRequires:  golang(github.com/golang/protobuf/proto)
BuildRequires:  golang(github.com/golang/protobuf/protoc-gen-go/descriptor)
BuildRequires:  golang(github.com/golang/protobuf/ptypes)
BuildRequires:  golang(github.com/golang/protobuf/ptypes/any)
BuildRequires:  golang(github.com/golang/protobuf/ptypes/duration)
BuildRequires:  golang(github.com/golang/protobuf/ptypes/timestamp)
BuildRequires:  golang(github.com/golang/protobuf/ptypes/wrappers)
BuildRequires:  golang(github.com/iancoleman/strcase)
BuildRequires:  golang(github.com/lyft/protoc-gen-star)
BuildRequires:  golang(github.com/lyft/protoc-gen-star/lang/go)
BuildRequires:  golang(golang.org/x/net/context)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
%gobuild -o %{gobuilddir}/bin/protoc-gen-validate %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE NOTICE
%doc CODE_OF_CONDUCT.md rule_comparison.md README.md gogoproto/README.md
%doc java/RELEASING.md
%{_bindir}/*

%gopkgfiles

%changelog
* Thu Apr 09 20:18:18 +03 2020 ElXreno <elxreno@gmail.com> - 0.1.0-1
- Initial package

