# Generated by go2rpm 1
%bcond_without check

# https://github.com/cmaglie/pb
%global goipath         github.com/cmaglie/pb
Version:                1.0.27

%gometa

%global common_description %{expand:
Console progress bar for Golang.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Console progress bar for Golang

# Upstream license specification: BSD-3-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/mattn/go-runewidth)
BuildRequires:  golang(golang.org/x/sys/unix)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/fatih/color)
BuildRequires:  golang(github.com/mattn/go-colorable)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Thu Apr 09 17:54:26 +03 2020 ElXreno <elxreno@gmail.com> - 1.0.27-1
- Initial package

