# Generated by go2rpm 1
%bcond_without check

# https://github.com/arduino/go-timeutils
%global goipath         github.com/arduino/go-timeutils
%global commit          d1dd9e313b1bfede35fe0bbf46d612e16a50e04e

%gometa

%global common_description %{expand:
Some useful functions to handle timezones in golang.}

%global golicenses      LICENSE.txt
Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Some useful functions to handle timezones in golang

License:        GPLv2
URL:            %{gourl}
Source0:        %{gosource}

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/require)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Thu Apr 09 17:49:56 +03 2020 ElXreno <elxreno@gmail.com> - 0-0.1.20200409gitd1dd9e3
- Initial package

