# Generated by go2rpm 1
# Disable check by default
%bcond_with check

# https://github.com/bugst/go-downloader
%global goipath         go.bug.st/downloader
%global forgeurl        https://github.com/bugst/go-downloader
Version:                1.2.0

%gometa

%global common_description %{expand:
Simple file downloader.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Simple file downloader

# Upstream license specification: BSD-3-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/require)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Thu Apr 09 18:25:39 +03 2020 ElXreno <elxreno@gmail.com> - 1.2.0-1
- Initial package

