# Generated by go2rpm 1
%bcond_without check

# https://github.com/codeclysm/cc
%global goipath         github.com/codeclysm/cc
Version:                1.2.2

%gometa

%global common_description %{expand:
A golang waitgroup with limits and error reporting.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        A golang waitgroup with limits and error reporting

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/fluxio/multierror)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Thu Apr 09 16:01:51 +03 2020 ElXreno <elxreno@gmail.com> - 1.2.2-1
- Initial package

