# Generated by go2rpm 1
%bcond_without check

# https://github.com/cncf/udpa
%global goipath         github.com/cncf/udpa
%global forgeurl        https://github.com/cncf/udpa/go
%global commit          e8cd3a4bb307e2c810cffff99f93e96e6d7fee85

%gometa

%global common_description %{expand:
Universal Data Plane API Working Group.}

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Universal Data Plane API Working Group

License:        ASL 2.0

URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/envoyproxy/protoc-gen-validate/validate)
BuildRequires:  golang(github.com/golang/protobuf/proto)
BuildRequires:  golang(github.com/golang/protobuf/protoc-gen-go/descriptor)
BuildRequires:  golang(github.com/golang/protobuf/ptypes)
BuildRequires:  golang(github.com/golang/protobuf/ptypes/duration)
BuildRequires:  golang(github.com/golang/protobuf/ptypes/struct)
BuildRequires:  golang(google.golang.org/grpc)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Fri Apr 10 13:43:19 +03 2020 ElXreno <elxreno@gmail.com> - 0-0.1.20200410gite8cd3a4
- Updated to commit e8cd3a4bb307e2c810cffff99f93e96e6d7fee85

* Thu Apr 09 20:24:56 +03 2020 ElXreno <elxreno@gmail.com> - 0-0.1.20200409gite8cd3a4
- Initial package
