# Generated by go2rpm 1
%bcond_without check

# https://github.com/bugst/go-cleanup
%global goipath         go.bug.st/cleanup
%global forgeurl        https://github.com/bugst/go-cleanup
Version:                1.0.0

%gometa

%global common_description %{expand:
This library provides a signal.Interrupt/CTRL-C interruptable context for
golang.}

%global golicenses      LICENSE
Name:           %{goname}
Release:        1%{?dist}
Summary:        This library provides a signal.Interrupt/CTRL-C interruptable context for golang

# Upstream license specification: BSD-3-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Thu Apr 09 18:24:28 +03 2020 ElXreno <elxreno@gmail.com> - 1.0.0-1
- Initial package

