# Generated by go2rpm 1
%bcond_without check

# https://github.com/arduino/board-discovery
%global goipath         github.com/arduino/board-discovery
%global commit          1ba29327fb0cd77c44823490c43433475f5379c6

%gometa

%global common_description %{expand:
# FIXME}

%global golicenses      LICENSE
%global godocs          README.adoc

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        None

License:        GPL-2.0-only
# FIXME: Upstream uses unknown SPDX tag GPL-2.0-only!
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/codeclysm/cc)
BuildRequires:  golang(github.com/juju/errors)
BuildRequires:  golang(github.com/oleksandr/bonjour)
BuildRequires:  golang(go.bug.st/serial.v1/enumerator)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Thu Apr 09 15:54:26 +03 2020 ElXreno <elxreno@gmail.com> - 0-0.1.20200409git1ba2932
- Initial package

