# Generated by go2rpm 1
# Disable check by default
%bcond_with check

# https://github.com/juju/errors
%global goipath         github.com/juju/errors
%global commit          3fe23663418fc1d724868c84f21b7519bbac7441

%gometa

%global common_description %{expand:
Common juju errors and functions to annotate errors.  Based on juju/errgo.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Common juju errors and functions to annotate errors.  Based on juju/errgo

License:        LGPLv3
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Thu Apr 09 16:58:09 +03 2020 ElXreno <elxreno@gmail.com> - 0-0.1.20200409git3fe2366
- Initial package

