# Generated by go2rpm 1
%bcond_without check

# https://github.com/arduino/go-properties-orderedmap
%global goipath         github.com/arduino/go-properties-orderedmap
Version:                1.0.0

%gometa

%global common_description %{expand:
Helper functions to handle ordered maps of hierarchical properties.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Helper functions to handle ordered maps of hierarchical properties

License:        GPLv2
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/arduino/go-paths-helper)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/require)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Thu Apr 09 17:46:49 +03 2020 ElXreno <elxreno@gmail.com> - 1.0.0-1
- Initial package

