# Generated by go2rpm 1
%bcond_without check

# https://github.com/spf13/cobra
%global goipath         github.com/spf13/cobra
Version:                0.0.7

%gometa

%global common_description %{expand:
A Commander for modern Go CLI interactions.}

%global golicenses      LICENSE.txt cobra/cmd/license_agpl.go\\\
                        cobra/cmd/license_bsd_clause_3.go\\\
                        cobra/cmd/license_apache_2.go\\\
                        cobra/cmd/license_mit.go cobra/cmd/licenses.go\\\
                        cobra/cmd/license_lgpl.go\\\
                        cobra/cmd/license_bsd_clause_2.go\\\
                        cobra/cmd/license_gpl_2.go cobra/cmd/license_gpl_3.go
%global godocs          doc bash_completions.md zsh_completions.md README.md\\\
                        powershell_completions.md cobra/README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        A Commander for modern Go CLI interactions

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/cpuguy83/go-md2man/v2/md2man)
BuildRequires:  golang(github.com/mitchellh/go-homedir)
BuildRequires:  golang(github.com/spf13/pflag)
BuildRequires:  golang(github.com/spf13/viper)
BuildRequires:  golang(gopkg.in/yaml.v2)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in cobra/tpl cobra; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE.txt cobra/cmd/license_agpl.go
%license cobra/cmd/license_bsd_clause_3.go cobra/cmd/license_apache_2.go
%license cobra/cmd/license_mit.go cobra/cmd/licenses.go
%license cobra/cmd/license_lgpl.go cobra/cmd/license_bsd_clause_2.go
%license cobra/cmd/license_gpl_2.go cobra/cmd/license_gpl_3.go
%doc doc bash_completions.md zsh_completions.md README.md
%doc powershell_completions.md cobra/README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Fri Apr 10 14:44:45 +03 2020 ElXreno <elxreno@gmail.com> - 0.0.7-1
- Initial package

