# Generated by go2rpm 1
%bcond_without check

# https://github.com/grpc/grpc-go
%global goipath         google.golang.org/grpc
%global forgeurl        https://github.com/grpc/grpc-go
Version:                1.28.1
%global tag             v%{version}

%gometa

%global common_description %{expand:
The Go language implementation of gRPC. HTTP/2 based RPC.}

%global golicenses      LICENSE
%global godocs          examples MAINTAINERS.md CODE-OF-CONDUCT.md\\\
                        GOVERNANCE.md AUTHORS README.md CONTRIBUTING.md\\\
                        reflection/README.md\\\
                        reflection/grpc_testingv3/README.md\\\
                        Documentation/compression.md\\\
                        Documentation/log_levels.md\\\
                        Documentation/versioning.md Documentation/encoding.md\\\
                        Documentation/concurrency.md Documentation/rpc-\\\
                        errors.md Documentation/keepalive.md\\\
                        Documentation/proxy.md Documentation/gomock-\\\
                        example.md Documentation/server-reflection-\\\
                        tutorial.md Documentation/grpc-auth-support.md\\\
                        Documentation/grpc-metadata.md\\\
                        Documentation/benchmark.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        The Go language implementation of gRPC. HTTP/2 based RPC

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/envoyproxy/go-control-plane/envoy/api/v2)
BuildRequires:  golang(github.com/envoyproxy/go-control-plane/envoy/api/v2/core)
BuildRequires:  golang(github.com/envoyproxy/go-control-plane/envoy/api/v2/endpoint)
BuildRequires:  golang(github.com/envoyproxy/go-control-plane/envoy/api/v2/route)
BuildRequires:  golang(github.com/envoyproxy/go-control-plane/envoy/config/filter/network/http_connection_manager/v2)
BuildRequires:  golang(github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2)
BuildRequires:  golang(github.com/envoyproxy/go-control-plane/envoy/service/load_stats/v2)
BuildRequires:  golang(github.com/envoyproxy/go-control-plane/envoy/type)
BuildRequires:  golang(github.com/envoyproxy/protoc-gen-validate/validate)
BuildRequires:  golang(github.com/golang/glog)
BuildRequires:  golang(github.com/golang/mock/gomock)
BuildRequires:  golang(github.com/golang/protobuf/jsonpb)
BuildRequires:  golang(github.com/golang/protobuf/proto)
BuildRequires:  golang(github.com/golang/protobuf/protoc-gen-go/descriptor)
BuildRequires:  golang(github.com/golang/protobuf/ptypes)
BuildRequires:  golang(github.com/golang/protobuf/ptypes/any)
BuildRequires:  golang(github.com/golang/protobuf/ptypes/duration)
BuildRequires:  golang(github.com/golang/protobuf/ptypes/struct)
BuildRequires:  golang(github.com/golang/protobuf/ptypes/timestamp)
BuildRequires:  golang(github.com/golang/protobuf/ptypes/wrappers)
BuildRequires:  golang(github.com/google/go-cmp/cmp)
BuildRequires:  golang(golang.org/x/net/http2)
BuildRequires:  golang(golang.org/x/net/http2/hpack)
BuildRequires:  golang(golang.org/x/net/trace)
BuildRequires:  golang(golang.org/x/oauth2)
BuildRequires:  golang(golang.org/x/oauth2/google)
BuildRequires:  golang(golang.org/x/oauth2/jwt)
BuildRequires:  golang(golang.org/x/sys/unix)
BuildRequires:  golang(google.golang.org/genproto/googleapis/rpc/code)
BuildRequires:  golang(google.golang.org/genproto/googleapis/rpc/errdetails)
BuildRequires:  golang(google.golang.org/genproto/googleapis/rpc/status)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/envoyproxy/go-control-plane/envoy/config/listener/v2)
BuildRequires:  golang(github.com/google/go-cmp/cmp/cmpopts)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in interop/xds/client interop/http2 interop/xds/server interop/grpclb_fallback interop/server benchmark/benchmain interop/alts/server stress/metrics_client stress/client benchmark/client benchmark/benchresult interop/client interop/alts/client benchmark/worker benchmark/server interop/fake_grpclb; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc examples MAINTAINERS.md CODE-OF-CONDUCT.md GOVERNANCE.md AUTHORS README.md
%doc CONTRIBUTING.md reflection/README.md reflection/grpc_testingv3/README.md
%doc Documentation/compression.md Documentation/log_levels.md
%doc Documentation/versioning.md Documentation/encoding.md
%doc Documentation/concurrency.md Documentation/rpc-errors.md
%doc Documentation/keepalive.md Documentation/proxy.md
%doc Documentation/gomock-example.md Documentation/server-reflection-tutorial.md
%doc Documentation/grpc-auth-support.md Documentation/grpc-metadata.md
%doc Documentation/benchmark.md
%{_bindir}/*

%gopkgfiles

%changelog
* Thu Apr 09 19:13:26 +03 2020 ElXreno <elxreno@gmail.com> - v1.28.1-1
- Initial package

