# Generated by go2rpm 1
%bcond_without check

# https://github.com/bugst/relaxed-semver
%global goipath         go.bug.st/relaxed-semver
%global forgeurl        https://github.com/bugst/relaxed-semver
%global commit          391e10178d18ddf8f579311f6a8f137be13ec4f5

%gometa

%global common_description %{expand:
A golang library to handle semver.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        A golang library to handle semver

# Upstream license specification: BSD-3-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/require)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Thu Apr 09 18:26:13 +03 2020 ElXreno <elxreno@gmail.com> - 0-0.1.20200409git391e101
- Initial package

