# Generated by go2rpm 1
# Disable check by default
%bcond_with check

# https://github.com/lyft/protoc-gen-star
%global goipath         github.com/lyft/protoc-gen-star
Version:                0.4.14

%gometa

%global common_description %{expand:
Protoc plugin library for efficient proto-based code generation.}

%global golicenses      LICENSE
%global godocs          CODE_OF_CONDUCT.md README.md protoc-gen-\\\
                        debug/README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Protoc plugin library for efficient proto-based code generation

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/golang/protobuf/proto)
BuildRequires:  golang(github.com/golang/protobuf/protoc-gen-go/descriptor)
BuildRequires:  golang(github.com/golang/protobuf/protoc-gen-go/generator)
BuildRequires:  golang(github.com/golang/protobuf/protoc-gen-go/plugin)
BuildRequires:  golang(github.com/spf13/afero)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/golang/protobuf/descriptor)
BuildRequires:  golang(github.com/golang/protobuf/ptypes/any)
BuildRequires:  golang(github.com/stretchr/testify/assert)
BuildRequires:  golang(github.com/stretchr/testify/require)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in protoc-gen-debug; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc CODE_OF_CONDUCT.md README.md protoc-gen-debug/README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Thu Apr 09 19:32:44 +03 2020 ElXreno <elxreno@gmail.com> - 0.4.14-1
- Initial package

