# Generated by go2rpm 1
%bcond_without check

# https://github.com/oleksandr/bonjour
%global goipath         github.com/oleksandr/bonjour
%global commit          5dcf00d8b228be86307f952f550f2191d956b9e2

%gometa

%global common_description %{expand:
MDNS/DNS-SD (also known as Apple Bonjour) library for Go (in pure Go).}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        MDNS/DNS-SD (also known as Apple Bonjour) library for Go (in pure Go)

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/miekg/dns)
BuildRequires:  golang(golang.org/x/net/ipv4)
BuildRequires:  golang(golang.org/x/net/ipv6)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Thu Apr 09 17:16:18 +03 2020 ElXreno <elxreno@gmail.com> - 0-0.1.20200409git5dcf00d
- Initial package

