# Generated by go2rpm 1
%bcond_without check

# https://github.com/arduino/go-win32-utils
%global goipath         github.com/arduino/go-win32-utils
%global commit          ed041402e83b924251a5d65b4dfeb727c480c359

%gometa

%global common_description %{expand:
A library for WIN32 API calls.}

%global golicenses      LICENSE.txt
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        A library for WIN32 API calls

License:        GPLv2

URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Thu Apr 09 18:41:04 +03 2020 ElXreno <elxreno@gmail.com> - 0-0.1.20200409gited04140
- Initial package

